import type { UniversalProduct } from '~/shared/api'

export type ProductToSearch = {
  name: string
  needCount: number
}

export const mockProductsToSearch: ProductToSearch[] = [
  { name: "Порошок стиральный Автомат (Ariel Color, 15 кг)", needCount: 75 },
  { name: "Гель для стирки черного белья Ariel Revitalblack, 1.04 л", needCount: 12 },
  { name: "Кондиционер-ополаскиватель для белья Вернель «Свежий бриз», 1.82 л", needCount: 16 },
  { name: "Мыло туалетное (банное)", needCount: 50 },
  { name: "Мыло хозяйственное", needCount: 30 },
  { name: "Жидкое крем-мыло Palila 500 мл аромат океана", needCount: 30 },
  { name: "Vanish средство для ручной чистки для ковров, 450 мл", needCount: 18 },
  { name: "Domestos Чистящее средство для унитаза, ультра белый антибактериальный эффект, 1500 мл", needCount: 6 },
  { name: "Чистящее средство для ванной от известкового налета и ржавчины Cillit Bang, 750 мл", needCount: 18 },
  { name: "Средство для прочистки труб от засоров «Bagi Потхан»", needCount: 12 },
  { name: "Таблетки для посудомоечных машин, 100 шт/упаковка", needCount: 3 },
  { name: "Средство для мытья посуды Fairy Сочный лимон, 1.35 л", needCount: 18 },
  { name: "Освежитель воздуха Glade, 300 мл (в ассортименте)", needCount: 18 },
  { name: "Mr Muscle средство для стекол и поверхностей, 530 мл", needCount: 8 },
  { name: "Средство для чистки плит и духовок Laima Professional Антижир, 500 мл", needCount: 8 },
  { name: "Зубочистки деревянные, 200 шт/упаковка", needCount: 10 },
  { name: "Фольга пищевая 50 м прочная", needCount: 10 },
  { name: "Пищевая пленка в рулоне плотная стрейч 30 см x 500 м", needCount: 5 },
  { name: "Пакеты фасовочные 30x40 см, 12 мкм, 500 шт/упаковка", needCount: 3 },
  { name: "Туалетная бумага 3-слойная, Papia", needCount: 192 },
  { name: "Пакеты для мусора 35 л, 50 шт/рулон, 8–10 мкм", needCount: 50 },
  { name: "Пакеты для мусора 120 л, 50 шт/рулон, 40–50 мкм", needCount: 30 },
  { name: "Полотенце кухонное вафельное, цветное 40x60 см", needCount: 6 },
  { name: "Полотенца бумажные Papia, белые, 3 слоя, 4 рулона/упаковка", needCount: 18 },
  { name: "Бумажные полотенца Tork Advanced H3 290184, листовые, 2 слоя, белые, 200 шт/упаковка", needCount: 8 },
  { name: "Салфетки бумажные (буфетные), 100 шт/упаковка", needCount: 60 },
  { name: "Губка для мытья посуды, средняя", needCount: 25 },
  { name: "Салфетка из микрофибры впитывающая, 30x30 см", needCount: 25 },
  { name: "Перчатки латексные хозяйственные XL", needCount: 10 },
  { name: "Перчатки нитриловые одноразовые, размер XL, 100 шт/упаковка", needCount: 3 },
  { name: "Веник", needCount: 6 },
  { name: "Совок со щеткой, для уборки помещений", needCount: 6 },
  { name: "Фильтр водяной для кофемашины Delonghi Eletta Cappuccino", needCount: 2 },
  { name: "Жидкость для очистки кофемашины Delonghi", needCount: 2 },
]
export const mockProducts: UniversalProduct[] = [
  {
    id: 'komus-1001',
    provider: 'komus',
    name: 'Бумага офисная А4, 500 листов',
    description: 'Классическая офисная бумага для печати',
    manifacturer: 'Komus',
    brand: 'Komus',
    sku: '1001',
    barcodes: ['4601234567890'],
    prices: { retail: 420.0, partner: 350.0 },
  },
  {
    id: 'komus-1002',
    provider: 'komus',
    name: 'Скрепки металлические 28 мм, 100 шт.',
    description: 'Офисные скрепки стандартного размера',
    manifacturer: 'Komus',
    sku: '1002',
    barcodes: ['4601234567891'],
    brand: 'TRTT',
    prices: { retail: 55.0, partner: 45.0 },
  },
  {
    id: 'komus-1003',
    provider: 'komus',
    name: 'Папка-регистратор А4, 75 мм',
    description: 'Плотный картон, ламинированное покрытие',
    manifacturer: 'Komus',
    sku: '1003',
    barcodes: ['4601234567892'],
    prices: { retail: 210.0, partner: 180.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1004',
    provider: 'komus',
    name: 'Ручка шариковая синяя',
    description: 'Корпус прозрачный, стержень сменный',
    manifacturer: 'Komus',
    sku: '1004',
    barcodes: ['4601234567893'],
    prices: { retail: 25.0, partner: 18.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1005',
    provider: 'komus',
    name: 'Маркер перманентный черный',
    description: 'Для письма по любым поверхностям',
    manifacturer: 'Komus',
    sku: '1005',
    barcodes: ['4601234567894'],
    prices: { retail: 70.0, partner: undefined },
    brand: 'TRTT',
  },
  {
    id: 'komus-1006',
    provider: 'komus',
    name: 'Папка на резинке пластиковая',
    description: 'Формат А4, прозрачная',
    manifacturer: 'Komus',
    sku: '1006',
    barcodes: ['4601234567895'],
    prices: { retail: 95.0, partner: 80.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1007',
    provider: 'komus',
    name: 'Степлер №24/6',
    description: 'Металлический корпус, до 25 листов',
    manifacturer: 'Komus',
    sku: '1007',
    barcodes: ['4601234567896'],
    prices: { retail: 310.0, partner: 270.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1008',
    provider: 'komus',
    name: 'Скотч упаковочный 48 мм × 66 м',
    description: 'Прозрачный, акриловый клей',
    manifacturer: 'Komus',
    sku: '1008',
    barcodes: ['4601234567897'],
    prices: { retail: 130.0, partner: 115.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1009',
    provider: 'komus',
    name: 'Папка-скоросшиватель, картон',
    description: 'Формат А4, без арматуры',
    manifacturer: 'Komus',
    sku: '1009',
    barcodes: ['4601234567898'],
    prices: { retail: 18.0, partner: 14.0 },
    brand: 'TRTT',
  },
  {
    id: 'komus-1010',
    provider: 'komus',
    name: 'Калькулятор настольный 12-разрядный',
    description: 'Питание от батарейки и солнечной панели',
    manifacturer: 'Komus',
    sku: '1010',
    barcodes: ['4601234567899'],
    prices: { retail: 950.0, partner: 800.0 },
    brand: 'TRTT',
  },
  // ===== SAMSON =====
  {
    id: 'samson-2001',
    provider: 'samson',
    name: 'Салфетки бумажные 100 шт.',
    description: 'Белые двухслойные салфетки',
    manifacturer: 'Samson',
    sku: '2001',
    barcodes: ['4698765432100'],
    prices: { retail: 95.0, partner: 80.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2002',
    provider: 'samson',
    name: 'Мыло жидкое 500 мл',
    description: 'Жидкое мыло с дозатором',
    manifacturer: 'Samson',
    sku: '2002',
    barcodes: ['4698765432101'],
    prices: { retail: 130.0, partner: 110.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2003',
    provider: 'samson',
    name: 'Полотенца бумажные 2 рулона',
    description: 'Двухслойные, белые',
    manifacturer: 'Samson',
    sku: '2003',
    barcodes: ['4698765432102'],
    prices: { retail: 120.0, partner: 100.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2004',
    provider: 'samson',
    name: 'Туалетная бумага 4 рулона',
    description: 'Двухслойная, белая',
    manifacturer: 'Samson',
    sku: '2004',
    barcodes: ['4698765432103'],
    prices: { retail: 160.0, partner: 140.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2005',
    provider: 'samson',
    name: 'Чай черный в пакетиках, 100 шт.',
    description: 'Классический байховый чай',
    manifacturer: 'Samson',
    sku: '2005',
    barcodes: ['4698765432104'],
    prices: { retail: 240.0, partner: 200.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2006',
    provider: 'samson',
    name: 'Кофе растворимый 100 г',
    description: 'Среднеобжаренный, стеклянная банка',
    manifacturer: 'Samson',
    sku: '2006',
    barcodes: ['4698765432105'],
    prices: { retail: 350.0, partner: 310.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2007',
    provider: 'samson',
    name: 'Сахар песок 1 кг',
    description: 'Фасованный в пакет',
    manifacturer: 'Samson',
    sku: '2007',
    barcodes: ['4698765432106'],
    prices: { retail: 95.0, partner: 85.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2008',
    provider: 'samson',
    name: 'Вода питьевая 5 л',
    description: 'Негазированная, пластик',
    manifacturer: 'Samson',
    sku: '2008',
    barcodes: ['4698765432107'],
    prices: { retail: 130.0, partner: 115.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2009',
    provider: 'samson',
    name: 'Мусорные пакеты 60 л, 20 шт.',
    description: 'Черные, прочные',
    manifacturer: 'Samson',
    sku: '2009',
    barcodes: ['4698765432108'],
    prices: { retail: 145.0, partner: 125.0 },
    brand: 'TRTT',
  },
  {
    id: 'samson-2010',
    provider: 'samson',
    name: 'Средство для мытья посуды 1 л',
    description: 'Лимон, концентрат',
    manifacturer: 'Samson',
    sku: '2010',
    barcodes: ['4698765432109'],
    prices: { retail: 160.0, partner: 140.0 },
    brand: 'TRTT',
  },
]
